# Generated by Django 4.2.1 on 2023-06-07 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productobanner_alter_producto_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoBanner',
        ),
    ]
